lantronix :
    # network addresses
    bellows :
        ip : '128.114.17.188'
        port : 10001
    w_lamp :
        ip : '128.114.17.186'
        port : 10002

ccd_controller0:
    # the name of the service config section MUST match the service name
    # this is how the qe machine knows the service name
    ktl_service_name : 'shanegcam'
    controller_type : 'andorcam'
    startup_config :
        # this section is interpreted as ktl keyword:value pairs
        # ktl keywords can be arbitrary, but must match actual keywords in the service
        # make this section generic, if possible
        # making it generic isn't really feasible
        # put an inital configuration here if desired
        EXPOSURE : 1.0
        GAINMODE : 0
        READSPEED : '1.0MHz'
        # put whatever keywords that have a controller function here
        # FILENAME :
        OBSMODE : 'Other'


ccd_controller1:
    # in the unlikely event you want to run a second CCD:
    # make another constructor function, one that accesses a whole
    # different config section, e.g., ccd_controller1
    ktl_service_name: 'Andor_test_cam'
    controller_type: 'andorcam'
    startup_config:
        # ktl keywords for startup go here
        # make this section generic, if possible
        expos_time: 1.0
        overscan: pass
        gain: 1
        hbin: 1
        vbin: 1
        numrows:
        numcols:
        window:
        readoutspeed:




tungsten_ps:
    name: bk_precision
    foo: value
