network :
    bellows :
        ip : '128.114.17.188'
        port : 10001
    w_lamp :
        ip : '128.114.17.186'
        port : 10002

service:
    # the name of the service config section MUST match the service name: this is how the qe machine knows the service name
    andor_test_cam:
        service_type: 'ixon_888'
